### ISSUE TITLE
Compat w/ Actually Additions Jams

### ISSUE THREAD

**Issue by WenXin20** [TheIllusiveC4/CulinaryConstruct#32]
[Actually Additions](https://www.curseforge.com/minecraft/mc-mods/actually-additions)  has several Jams that provide potion effects when eaten, but when placed in a sandwich, the potion effects are not applied when the sandwich is eaten. Is compat possible?

**Comment by TheIllusiveC4** [comment]
Unfortunately, compatibility isn't really feasible from my end. This is because the Jams call `Item#onItemUseFinish` instead of `ItemFood#onFoodEaten` to apply the potion effects. The latter is what vanilla uses for food potion effects so that's what I use, and trying to call `Item#onItemUseFinish` instead from my end could cause unwanted side effects.
