### ISSUE TITLE
[1.14] Use tag 'forge:bowls/wooden' instead of just 'forge:bowl'

### ISSUE THREAD

**Issue by Wabbit0101** [TheIllusiveC4/CulinaryConstruct#33]
**Please describe the new feature or change.**
Unless you're tracking the actual underlying bowl (which you might be), can the mod use the more specific 'forge:bowls/wooden'?

**Please describe why you want this feature.**
From my own limited work with integration tags there is already: 'bowls/wooden', 'bowls/terracotta', 'bowls/golden', and 'bowls/glass' tags floating around.

**Comment by TheIllusiveC4** [comment]
Any bowl should be valid, so there's no reason to limit it to just wooden ones. That's why it's left generic.

Although, while we're on this subject, I should rename the tag to be "bowls" plural instead of "bowl" to match the current forge tag naming scheme.

Anything that's adding specific tags for different types of bowls should also be adding all of them to the umbrella "bowls" tag, like how Forge handles many of the tags already.
