### ISSUE TITLE
[1.14.4] Apple skin and Quark not showing hunger point on Culinary Construct sandwiches and bowls

### ISSUE THREAD

**Issue by TBiscuit1** [TheIllusiveC4/CulinaryConstruct#34]
#### Versions (Be specific, do not write "latest"):
* Culinary Construct: culinaryconstruct-FORGE-1.14.4-2.0-beta2
* Apple Skin: AppleSkin-mc1.14.4-forge-1.0.13
* Forge: forge-28.2.3
#### Observed Behavior:
Food from Culinary Construct doesn't show there hunger points with Apple Skin
#### Expected Behavior:
That they show there food points
#### Steps to Reproduce:
I don't think I need to write the steps, it's kind of obvious

Crash Log: Please use a paste site like [hastebin](https://hastebin.com/).
No Crash

Also, I referenced this issue to the Apple Skin issues

**Comment by TheIllusiveC4** [comment]
This is a bit of an odd issue. Both mods are functioning correctly. This is due to the fact that Minecraft changed the way they construct food items and these changes created a loss in ability to create dynamic food values. This is a vital feature of Culinary Construct so I had to do a workaround where I create dummy food values and directly add the correct values to the food stats myself. Apple Skin obviously can't read that, it just goes off the dummy food values that I provide.

There's not a whole lot I can do on my end, unless someone can help me figure out another workaround that creates dynamic food values in a way that passes the correct value to the food builder. From my perspective, the easiest way would be if Apple Skin provided an API or something that I can hook into to give it the right values.

**Comment by TBiscuit1** [comment]
Just realized the same bug goes to Quark too, gonna tell him

**Comment by TBiscuit1** [comment]
Quark Version : Quark-r2.0-212

**Comment by BJZ2** [comment]
Perhaps the easiest thing you could do is to add or extend a tooltip with food/hunger and saturation info. Make it optional or change "Hold [Shift] for Ingredients" to "Hold [Shift] for Ingredients and Info".

**Comment by Dr-WeiAL** [comment]
Has this problem been going on for so long? 1.16.5 also has this problem

**Comment by TheIllusiveC4** [comment]
This problem doesn't really have a way to solve it right now, which is why it's still an open issue. As mentioned before, this is due to the fact that Minecraft changed the way it handled food and dynamic food information currently cannot be passed to other mods due to the workaround needed.

The best solution as it is right now is what BJZ2 mentioned above adding it as a tooltip to Culinary Construct, which is what I'll be looking into in the near future.

**Comment by TheIllusiveC4** [comment]
I've released an update on 1.18.2 and 1.16.5 that has new AppleSkin integration which should solve the tooltip discrepancies. I didn't realize that AppleSkin had introduced an API that allows for a fix on my end, so apologies for the wait on that. 

As for Quark and potentially other mods, they don't have such an API so that will still be an ongoing issue that won't be addressed unless that changes. However, as a stopgap solution for those that aren't using AppleSkin, I've added a new configurable tooltip option that allows the sandwiches and food bowls to show their nutrition information.

Forge has recently merged a new feature that allows for dynamic food properties once again on 1.18.2, so any mod on 1.18.2 or later that encounters this issue with Culinary Construct should update to Forge 40.0.47 or later and integrate with the new food properties methods.

**Comment by Dr-WeiAL** [comment]
> I've released an update on 1.18.2 and 1.16.5 that has new AppleSkin integration which should solve the tooltip discrepancies. I didn't realize that AppleSkin had introduced an API that allows for a fix on my end, so apologies for the wait on that.
> 
> As for Quark and potentially other mods, they don't have such an API so that will still be an ongoing issue that won't be addressed unless that changes. However, as a stopgap solution for those that aren't using AppleSkin, I've added a new configurable tooltip option that allows the sandwiches and food bowls to show their nutrition information.
> 
> Forge has recently merged a new feature that allows for dynamic food properties once again on 1.18.2, so any mod on 1.18.2 or later that encounters this issue with Culinary Construct should update to Forge 40.0.47 or later and integrate with the new food properties methods.

Haven't passed the audit yet?
I don't see an update on curseforge, anyway, I'll try to build one first
