### ISSUE TITLE
Stack Creation Buck

### ISSUE THREAD

**Issue by Pontiac76** [TheIllusiveC4/CulinaryConstruct#57]
#### Versions (Be specific, do not write "latest"):
* Culinary Construct: 4.0.0.6
* Forge: 1.16.5-36.2.19
#### Observed Behavior:
Shift-Clicking the final meal yields a stack of 64 *4 (For fully kitted sandwich) of the food of your making.

#### Expected Behavior:
Stack of 4 (For a fully kitted meal) was expected to be pulled out.  If I just click on the final food, I get the max of 4 as indicated on the main CurseForge site and in the UI.

#### Steps to Reproduce:
1. Fill up the station with whatever food
2. Shift-click the final food
3. Stack of 64*4 sitting in my inventory?
...

Crash Log: Please use a paste site like [hastebin](https://hastebin.com/).

No crash log.  However, I'm wondering if this is INTENTIONAL game play or if this is an over site?  I also noticed that despite the limit of 4 in the stations UI, I can still stack the sandwiches to 64 so long they're the exact same sandwich with the same name, etc. (Same metadata)

**Comment by TheIllusiveC4** [comment]
If I'm understanding this correctly, then it's intentional. Shift-clicking the output will use as many ingredients as possible to create as many sandwiches as possible. Clicking normally will only use the ingredients once, to make the stack of 4 in your case. 

Stack sizes to 64 are normal. The initial stack size is just how many one set of ingredients can make.
