### ISSUE TITLE
Craft pizza

### ISSUE THREAD

**Issue by Ozzymud** [TheIllusiveC4/CulinaryConstruct#60]
Craft pizzas same as soups/sandwiches.

Maybe have a 3rd base item to specify it's a pizza like dough or something. They could also be either whole pizzas that have a durability or maybe crafted as slices... more slices crafted per quality like sandwiches now.

I can see it now... Meat Lovers, BBQ, Ham & Pineapple, Supreme, etc etc!

**Comment by TheIllusiveC4** [comment]
While it is a fun idea, I'm already considering adding cakes as a 3rd item type and there's a lot of overlap between cakes and pizzas. Not thematically of course, but mechanically: a place-able item that can be eaten in intervals. And if it comes down to cakes vs. pizzas, I'd prefer cakes because they are already present in the vanilla game.
